language: node_js
node_js: stable

branches:
  only:
    - develop

env:
  global:
    - GH_REF: https://github.com/luismayta/slides-ioc-challenger.git
    - GH_BRANCH: gh-pages
    - USER_NAME: 'Luis Mayta'
    - USER_EMAIL: 'slovacus@gmail.com'

cache:
  directories:
    - $HOME/.yarn

before_install:
  - node --version
  - yarn --version

install:
  - yarn install

script:
  - yarn build

after_script:
  - cd ./public
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "Implement build for branch gh-pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
