# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    environment: &environment
      - STAGE=dev
    volumes:
      - .:/app
    env_file:
      - .env
